### ISSUE TITLE
problem? hi do you know how to solve this problem?

### ISSUE THREAD

**Issue by aaa-meituo-aaa** [Shamir-Lab/SCAPP#14] opened 2020-09-22 10:12 UTC
Filtering plasmids by plasmid-specific genes
No blast db provided, creating one
Running command: makeblastdb  -in circular/335-M._scapp_res/intermediate_files/335-M._contigs.cycs.fasta -dbtype nucl -out circular/335-M._scapp_res/in
termediate_files/hit_cycs/335-M._contigs.cycs.fasta.blastdb
Running blast search for gene (nt) sequences in blast db
Running command: blastn -task megablast -db circular/335-M._scapp_res/intermediate_files/hit_cycs/335-M._contigs.cycs.fasta.blastdb -query /mibi/users/
Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/data/nt/nt3 -out circular/335-M._scapp_res/intermediate_files/hit_cycs/nt3_blastdb.out -num_th
reads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
Running command: blastn -task megablast -db circular/335-M._scapp_res/intermediate_files/hit_cycs/335-M._contigs.cycs.fasta.blastdb -query /mibi/users/
Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/data/nt/nt1 -out circular/335-M._scapp_res/intermediate_files/hit_cycs/nt1_blastdb.out -num_th
reads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
Running command: blastn -task megablast -db circular/335-M._scapp_res/intermediate_files/hit_cycs/335-M._contigs.cycs.fasta.blastdb -query /mibi/users/
Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/data/nt/nt2 -out circular/335-M._scapp_res/intermediate_files/hit_cycs/nt2_blastdb.out -num_th
reads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
Running blast search for protein (aa) sequences in blast db
Running command: tblastn -db circular/335-M._scapp_res/intermediate_files/hit_cycs/335-M._contigs.cycs.fasta.blastdb -db_gencode 11 -query /mibi/users/
Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/data/aa/aa1 -out circular/335-M._scapp_res/intermediate_files/hit_cycs/aa1_blastdb.out -num_th
reads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
Error running tblastn. Check paths to tblastn executable and input files.
Error filtering by plasmid genes. Check BLAST output file (blast_std.log)

**Comment by dpellow** [comment] 2020-09-22 13:04
OK this says there is an error running BLAST. What does it say in the BLAST output file (logs/blast_std.log)?
This may be related to [this issue](https://github.com/Shamir-Lab/SCAPP/issues/12#issue-696816925). If so, you can fix it by updating the BLAST version like: `conda install -c bioconda blast=2.10.1`. Please let us know if that fixes the issue, we are waiting for approval for our bioconda recipe with this update to be registered.

**Comment by aaa-meituo-aaa** [comment] 2020-09-22 22:10
ok thanks, i will try it

**Comment by aaa-meituo-aaa** [comment] 2020-09-22 22:52
> OK this says there is an error running BLAST. What does it say in the BLAST output file (logs/blast_std.log)?
> This may be related to [this issue](https://github.com/Shamir-Lab/SCAPP/issues/12#issue-696816925). If so, you can fix it by updating the BLAST version like: `conda install -c bioconda blast=2.10.1`. Please let us know if that fixes the issue, we are waiting for approval for our bioconda recipe with this update to be registered.

Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Finding plasmid-specific genes with BLAST
No blast db provided, creating one
Running command: makeblastdb  -in assmebly_res/DP-Sample050-S46-001_contigs.fastg -dbtype nucl -out circular/DP-Sample050-S46-001_scapp_res/intermediate_files/DP-Sample050-S46-001_contigs.fastg.blastdb
Error creating blast database. Check path to makeblastdb executable.
Error finding plasmid genes - check BLAST output file (blast_std.log)

it is not working

**Comment by aaa-meituo-aaa** [comment] 2020-09-22 22:56
> OK this says there is an error running BLAST. What does it say in the BLAST output file (logs/blast_std.log)?
> This may be related to [this issue](https://github.com/Shamir-Lab/SCAPP/issues/12#issue-696816925). If so, you can fix it by updating the BLAST version like: `conda install -c bioconda blast=2.10.1`. Please let us know if that fixes the issue, we are waiting for approval for our bioconda recipe with this update to be registered.

and besides, this tool is quite sample-based, some samples can not run successfully, is this normal?

and about the version, which is the lastest one, i never run it successfully with version 0.1.3, but with 0.1.1

**Comment by dpellow** [comment] 2020-09-23 06:24
I see that the latest issue is that BLAST is not running at all. Maybe you don't have a working version of BLAST.
Can you please give us more information so that we can help solve this issue. Can you let us know:
1) What version of BLAST do you have? If you run the command `tblastn -h` it will tell you which version.
2) How did you install SCAPP, did you use bioconda ?
3) What is the command that you are using to run SCAPP?
4) Can you copy the contents of the blast error file here. It is logs/blast_std.log.
5) Can you clarify what you mean about the tool being sample based? What samples were able to run and which weren't?
6) What are the input files that you are using? They should be *assembly graphs* in *fastg format*.

Note that if you need to re-run SCAPP on the same input you can save time by using the BAM alignment file from a previous run instead of having SCAPP run the alignment again. This is done by passing the `-b <bamfile name>` parameter instead of passing the read files.

**Comment by dpellow** [comment] 2020-09-23 11:41
@aaa-meituo-aaa note that an updated recipe was just approved on bioconda. If you install again from bioconda that should ensure you have the correct version of BLAST.

**Comment by aaa-meituo-aaa** [comment] 2020-09-23 12:34
> @aaa-meituo-aaa note that an updated recipe was just approved on bioconda. If you install again from bioconda that should ensure you have the correct version of BLAST.

ok! i will try it later.
and i didn`t intall by conda,  i tried, but raise error, which error i forget, and then i  using yamlfile to install, like this:
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python=3.7
    - networkx=2.4
    - pysam=0.15.3
    - nose=1.3
    - numpy=1.17.4
#    - blast=2.10.1
    - plasclass

**Comment by aaa-meituo-aaa** [comment] 2020-09-23 12:38
> @aaa-meituo-aaa note that an updated recipe was just approved on bioconda. If you install again from bioconda that should ensure you have the correct version of BLAST.

Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Finding plasmid-specific genes with BLAST
Starting SCAPP plasmid finding
Traceback (most recent call last):
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/scapp.py", line 474, in <module>
    main()
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/scapp.py", line 347, in main
    PARAMS.MAX_CV, PARAMS.MIN_LENGTH)
  File "/mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/recycle.py", line 123, in run_scapp
    logger.info("Coverage threshold:%4f" % thresh)
NameError: name 'thresh' is not defined

this error is yestesday i runed the new version of scapp, hoping it is my problem, not scapp, you can also check this!

**Comment by dpellow** [comment] 2020-09-23 13:02
> ok! i will try it later.
> and i didn`t intall by conda, i tried, but raise error, which error i forget, and then i using yamlfile to install, like this:
OK, can you try to install with Bioconda or by following the installation instructions and let me know what happens

**Comment by dpellow** [comment] 2020-09-23 13:04
> this error is yestesday i runed the new version of scapp, hoping it is my problem, not scapp, you can also check this!
Can you clarify what this means? Are you seeing this error currently after installing the latest version?

**Comment by aaa-meituo-aaa** [comment] 2020-09-23 13:30
> @aaa-meituo-aaa note that an updated recipe was just approved on bioconda. If you install again from bioconda that should ensure you have the correct version of BLAST.

hi !

i installed scapp with conda (new version), 
the blast is update:   blast              bioconda/linux-64::blast-2.10.1-pl526he19e7b1_1
but still the same error:

   (scapp) hsv709@pallas:/mibi/Wanli/snakemake/final_pipeline/run_test$ scapp -g assmebly_res/DP-Sample049-S45-001_contigs.fastg -o circular/DP-Sample049-S45-001_scapp_res -k 121 -r1 qc_reads/DP-Sample049-S45-001_qc_1.fastq.gz -r2 qc_reads/DP-Sample049-S45-001_qc_2.fastq.gz -p 8


Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Finding plasmid-specific genes with BLAST
Error finding plasmid genes - check BLAST output file (blast_std.log)
Traceback (most recent call last):
  File "/mibi/Wanli/anaconda/envs/scapp/bin/scapp", line 10, in <module>
    sys.exit(main())
  File "/mibi/Wanli/anaconda/envs/scapp/lib/python3.7/site-packages/scapp/scapp.py", line 326, in main
    ncbi_path, num_procs, PARAMS.GENE_MATCH_THRESH)
  File "/mibi/users/Wanli/anaconda/envs/scapp/lib/python3.7/site-packages/scapp/find_plasmid_gene_matches.py", line 146, in find_plasmid_gene_matches
    dbpath = create_db(infile, ncbi_bin, outdir)
  File "/mibi/users/Wanli/anaconda/envs/scapp/lib/python3.7/site-packages/scapp/find_plasmid_gene_matches.py", line 66, in create_db
    subprocess.check_call(command, shell=True)
  File "/mibi/Wanli/anaconda/envs/scapp/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'makeblastdb  -in assmebly_res/DP-Sample049-S45-001_contigs.fastg -dbtype nucl -out circular/DP-Sample049-S45-001_scapp_res/intermediate_files/DP-Sample049-S45-001_contigs.fastg.blastdb' returned non-zero exit status 255.


and the blast_std.log :

No blast db provided, creating one
Running command: makeblastdb  -in assmebly_res/DP-Sample049-S45-001_contigs.fastg -dbtype nucl -out circular/DP-Sample049-S45-001_scapp_res/intermediate_files/DP-Sample049-S45-001_contigs.fastg.blastdb


Building a new DB, current time: 09/23/2020 15:23:49
New DB name:   /mibi/users/Wanli/snakemake/final_pipeline/run_test/circular/DP-Sample049-S45-001_scapp_res/intermediate_files/DP-Sample049-S45-001_contigs.fastg.blastdb
New DB title:  assmebly_res/DP-Sample049-S45-001_contigs.fastg
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B

No volumes were created.

Error: mdb_env_open: Cannot allocate memory
Error creating blast database. Check path to makeblastdb executable.


and later i will try with other data, see what will happen

**Comment by aaa-meituo-aaa** [comment] 2020-09-23 13:42
> > ok! i will try it later.
> > and i didn`t intall by conda, i tried, but raise error, which error i forget, and then i using yamlfile to install, like this:
> 
> OK, can you try to install with Bioconda or by following the installation instructions and let me know what happens



> > this error is yestesday i runed the new version of scapp, hoping it is my problem, not scapp, you can also check this!
> 
> Can you clarify what this means? Are you seeing this error currently after installing the latest version?

no, this error is with another data, but i don`t know whether it is the latest version, and i am re- running it with lastest now,

**Comment by dpellow** [comment] 2020-09-23 13:59
OK I don't see if this is the same problem as previously. I see here that BLAST's makeblastdb did not work. Can you verify the following for me:
- In the scapp conda environment type `tblastn -h` and let me know what version it says
- In the scapp conda environment run the makeblastdb command on its own: `makeblastdb -in assmebly_res/DP-Sample049-S45-001_contigs.fastg -dbtype nucl -out circular/DP-Sample049-S45-001_scapp_res/intermediate_files/DP-Sample049-S45-001_contigs.fastg.blastdb`
- Are you running this in Windows or Linux?
Thanks

**Comment by aaa-meituo-aaa** [comment] 2020-09-23 14:22
> * tblastn -h
USAGE
  tblastn [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-negative_seqidlist filename]
    [-taxids taxids] [-negative_taxids taxids] [-taxidlist filename]
    [-negative_taxidlist filename] [-entrez_query entrez_query]
    [-db_soft_mask filtering_algorithm] [-db_hard_mask filtering_algorithm]
    [-subject subject_input_file] [-subject_loc range] [-query input_file]
    [-out output_file] [-evalue evalue] [-word_size int_value]
    [-gapopen open_penalty] [-gapextend extend_penalty]
    [-qcov_hsp_perc float_value] [-max_hsps int_value]
    [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value]
    [-sum_stats bool_value] [-db_gencode int_value] [-ungapped]
    [-max_intron_length length] [-seg SEG_options]
    [-soft_masking soft_masking] [-matrix matrix_name]
    [-threshold float_value] [-culling_limit int_value]
    [-best_hit_overhang float_value] [-best_hit_score_edge float_value]
    [-subject_besthit] [-window_size int_value] [-lcase_masking]
    [-query_loc range] [-parse_deflines] [-outfmt format] [-show_gis]
    [-num_descriptions int_value] [-num_alignments int_value]
    [-line_length line_length] [-html] [-sorthits sort_hits]
    [-sorthsps sort_hsps] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-remote] [-comp_based_stats compo]
    [-use_sw_tback] [-in_pssm psi_chkpt_file] [-version]

DESCRIPTION
   Protein Query-Translated Subject BLAST 2.10.1+

2--------------------------------------------------------------------------------------------------------------------------------
(scapp) hsv709@pallas:/mibi/Wanli/snakemake/final_pipeline/run_test$ makeblastdb -in assmebly_res/DP-Sample049-S45-001_contigs.fastg -dbtype nucl -out circular/DP-Sample049-S45-001_scapp_res/intermediate_files/DP-Sample049-S45-001_contigs.fastg.blastdb

Building a new DB, current time: 09/23/2020 16:21:10
New DB name:   /mibi/users/Wanli/snakemake/final_pipeline/run_test/circular/DP-Sample049-S45-001_scapp_res/intermediate_files/DP-Sample049-S45-001_contigs.fastg.blastdb
New DB title:  assmebly_res/DP-Sample049-S45-001_contigs.fastg
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /mibi/users/Wanli/snakemake/final_pipeline/run_test/circular/DP-Sample049-S45-001_scapp_res/intermediate_files/DP-Sample049-S45-001_contigs.fastg.blastdb
Keep MBits: T
Maximum file size: 1000000000B

No volumes were created.

Error: mdb_env_open: Cannot allocate memory

in the linux

**Comment by dpellow** [comment] 2020-09-23 14:41
OK thanks for that info.
It seems like BLAST fails to create a database on your file. Does the same makeblastdb command work with other input files? The error that BLAST gives indicates there is not enough memory. What happens if you test it on a very small example (like just the first few lines of the input that failed)?

**Comment by aaa-meituo-aaa** [comment] 2020-09-23 19:40
> OK thanks for that info.
> It seems like BLAST fails to create a database on your file. Does the same makeblastdb command work with other input files? The error that BLAST gives indicates there is not enough memory. What happens if you test it on a very small example (like just the first few lines of the input that failed)? How big is the input file that causes the failure?
> 
> I found [this work around for a similar error](https://www.biostars.org/p/413294/#415002) in BLAST, but it seems that it is only relevant for Windows (maybe you can try to set the environment variable to the value in this post).
> Another problem might be if you are using a 32 bit system instead of 64-bit. Do you know?
> Or if you don't have write permissions to the output folder - can you test this?

hi, dpellow!
i tried with another data which is much more larger than  previous one, but same err
Getting scores of graph nodes
Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Creating BAM file of read mappings with BWA
Getting scores of graph nodes
Finding plasmid-specific genes with BLAST
No blast db provided, creating one
Running command: makeblastdb  -in assmebly_res/338-M._contigs.fastg -dbtype nucl -out circular/338-M._scapp_res/intermediate_files/338-M._contigs.fastg.blastdb
Error creating blast database. Check path to makeblastdb executable.
Error finding plasmid genes - check BLAST output file (blast_std.log)

the only version i runned successfully of scapp is 0.1.1, but even in v-0.1.1 some samples are still raise the error which is subprocess problem, maybe the  blast version problem.

**Comment by dpellow** [comment] 2020-09-23 21:14
> i tried with another data which is much more larger than previous one, but same err

Since this appears to be a memory problem, can you check with much **smaller** data - say just take the first 2-3 lines of the file


> Running command: makeblastdb -in assmebly_res/338-M._contigs.fastg -dbtype nucl -out circular/338-M._scapp_res/intermediate_files/338-M._contigs.fastg.blastdb
> Error creating blast database. Check path to makeblastdb executable.
> Error finding plasmid genes - check BLAST output file (blast_std.log)

This is still the same problem. In order to isolate what the issue is, can you run just the makeblastdb command line: `makeblastdb -in <input file> -dbtype nucl -out <output file>` in the conda environment of scapp.

From what I found online, this command may fail if you are on a 32-bit system instead of 64-bit or if you don't have permission to write to the output location. Can you confirm if this is the case? You can check the system with the commands `uname -m` or `arch` in the terminal. You can check if you have write permissions by trying `touch <output file>`.

If the system and permissions are ok but you still get the error can you try running makeblastdb as so: `makeblastdb -in <input file> -dbtype nucl -blastdb_version 4 -out <output file>` ? Please let me know if using db format 4 instead works.

> the only version i runned successfully of scapp is 0.1.1, but even in v-0.1.1 some samples are still raise the error which is subprocess problem, maybe the blast version problem.

I suggest only working with v-0.1.3. If there is confusion about having different versions on your system I suggest deleting all of them and doing a clean installation of v-0.1.3.

The issue you are seeing in v-0.1.1 is the same as issue #12 and is solved by using BLAST version 2.10.1. However, it seems that this version of BLAST is creating problems on your system. Hopefully one of the above options will solve that problem. Let us know! Thanks

**Comment by dpellow** [comment] 2020-09-25 13:50
@aaa-meituo-aaa  Did any of the above solve the issue?

**Comment by dpellow** [comment] 2020-10-06 09:51
@aaa-meituo-aaa  did one of the above solve the problem for you?

**Comment by aaa-meituo-aaa** [comment] 2020-10-07 08:59
sorry, dpellow! i just see the message, recently i do other things, i will
test it tomorrow, and tell you the result! thanks

dpellow <notifications@github.com> 于2020年10月6日周二 下午5:51写道：

**Comment by aaa-meituo-aaa** [comment] 2020-10-08 11:50
Hi, i run like you said, and here is the result, not raising error.  but i don`t know whether successful, because i didn`t find the output fasta file. 

(scapp) hsv709@pallas:/mibi/Wanli/test_scapp$ makeblastdb  -in DP-Sample031-S31-001_contigs.fastg -dbtype nucl -blastdb_version 4 -out sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb

Building a new DB, current time: 10/08/2020 13:45:18
New DB name:   /mibi/users/Wanli/test_scapp/sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb
New DB title:  DP-Sample031-S31-001_contigs.fastg
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /mibi/users/Wanli/test_scapp/sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 3300 sequences in 0.173132 seconds.

really sorry for answering so late

**Comment by dpellow** [comment] 2020-10-08 12:36
OK thanks! If I understood correctly you ran makeblastdb with BLAST 2.10.1 using the option `-blastdb_version 4`. Is that correct? 

You did not find the output files starting with sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb ?

What happens if you run the same command but without the `blastdb_version 4` option ?

**Comment by aaa-meituo-aaa** [comment] 2020-10-08 12:50
> OK thanks! If I understood correctly you ran `makeblastdb` with BLAST 2.10.1 adding the option `-blastdb_version 4`. Is that correct?
> 
> You did not find the output files starting with `sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb` ?
> 
> What happens if you run the same command but without the `blastdb_version 4` option ?

yes, i run makeblastdb with BLAST 2.10.1 adding the option -blastdb_version 4, just show the result that i show you. 

and what i said that i didn`t find the output is the final output file which contains predicted plasmids contig. the "<prefix>.confident_cycs.fasta" file, maybe because i only run "makedblastdb", of course can`t get the results. 

(scapp) hsv709@pallas:/mibi/Wanli/test_scapp/sacpp_darwin_old/intermediate_files$ ls
assembly_graph.nodes.scores                     DP-Sample031-S31-001_contigs.fastg.blastdb.ntf-lock
DP-Sample031-S31-001_contigs.fastg.blastdb      plasclass.out
DP-Sample031-S31-001_contigs.fastg.blastdb.ndb  reads_pe_primary.sort.bam
DP-Sample031-S31-001_contigs.fastg.blastdb.ntf  reads_pe_primary.sort.bam.bai


and if i didn`t run blastdb_version 4, it will still raise error.

**Comment by aaa-meituo-aaa** [comment] 2020-10-08 12:53
> > OK thanks! If I understood correctly you ran `makeblastdb` with BLAST 2.10.1 adding the option `-blastdb_version 4`. Is that correct?
> > You did not find the output files starting with `sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb` ?
> > What happens if you run the same command but without the `blastdb_version 4` option ?
> 
> yes, i run makeblastdb with BLAST 2.10.1 adding the option -blastdb_version 4, just show the result that i show you.
> 
> and what i said that i didn`t find the output is the final output file which contains predicted plasmids contig. the "<prefix>.confident_cycs.fasta" file, maybe because i only run "makedblastdb", of course can`t get the results.
> 
> (scapp) hsv709@pallas:/mibi/Wanli/test_scapp/sacpp_darwin_old/intermediate_files$ ls
> assembly_graph.nodes.scores DP-Sample031-S31-001_contigs.fastg.blastdb.ntf-lock
> DP-Sample031-S31-001_contigs.fastg.blastdb plasclass.out
> DP-Sample031-S31-001_contigs.fastg.blastdb.ndb reads_pe_primary.sort.bam
> DP-Sample031-S31-001_contigs.fastg.blastdb.ntf reads_pe_primary.sort.bam.bai
> 
> and if i didn`t run blastdb_version 4, it will still raise error.

will you change the codes in scapp to solve this problem? or i should do something individual works to solve this problem, to get the final "<prefix>.confident_cycs.fasta" file

**Comment by dpellow** [comment] 2020-10-08 13:50
Yes, that was just the makeblastdb command, not SCAPP. I will update the scapp code so that it should work for you, but I don't want to introduce any new problems so I want to make sure that it will work first.

After running the makeblastdb command to create the database can you try running tblastn:
`tblastn -db sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb -db_gencode 11 -query /mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/data/aa/aa1 -out sacpp_darwin/intermediate_files/hit_cycs/aa1_blastdb.out -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"`

Note - I'm not sure all the paths that I've listed here are still the same on your system or if you've changed them. Specifically: the `-db` option needs the path to the BLAST database you made with `makeblastdb` and the `-query` option needs the path to the file `aa1` under the directory `data/aa` in the scapp folder where SCAPP was installed.

Let me know if that works - if so, it should be a quick fix to SCAPP to have it use db_version 4.

**Comment by aaa-meituo-aaa** [comment] 2020-10-08 14:58
> tblastn -db sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb -db_gencode 11 -query /mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/data/aa/aa1 -out sacpp_darwin/intermediate_files/hit_cycs/aa1_blastdb.out -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"

i run the commend you give me, but it seems in "sacpp_darwin/intermediate_files/" don`t have "hit_cycs" folder, and i can`t "mkdir hit_cycs",  and if i changing the out path, like "sacpp_darwin/intermediate_files/aa1_blastdb.out", it will raise another error.

(scapp) hsv709@pallas:/mibi/Wanli/test_scapp$ tblastn -db sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb -db_gencode 11 -query /mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/data/aa/aa1 -out sacpp_darwin/intermediate_files/hit_cycs/aa1_blastdb.out -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
Command line argument error: Argument "out". File is not accessible:  `sacpp_darwin/intermediate_files/hit_cycs/aa1_blastdb.out'

(scapp) hsv709@pallas:/mibi/Wanli/test_scapp$ tblastn -db sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb -db_gencode 11 -query /mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/data/aa/aa1 -out sacpp_darwin/intermediate_files/aa1_blastdb.out -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
BLAST Database error: No alias or index file found for nucleotide database [sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb] in search path [/mibi/users/Wanli/test_scapp:/data/blast:]

**Comment by aaa-meituo-aaa** [comment] 2020-10-08 15:00
> Yes, that was just the makeblastdb command, not SCAPP. I will update the scapp code so that it should work for you, but I don't want to introduce any new problems so I want to make sure that it will work first.
> 
> After running the makeblastdb command to create the database can you try running tblastn:
> `tblastn -db sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb -db_gencode 11 -query /mibi/users/Wanli/snakemake/final_pipeline/F_pipeline/db/scapp/scapp/data/aa/aa1 -out sacpp_darwin/intermediate_files/hit_cycs/aa1_blastdb.out -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"`
> 
> Note - I'm not sure all the paths that I've listed here are still the same on your system or if you've changed them. Specifically: the `-db` option needs the path to the BLAST database you made with `makeblastdb` and the `-query` option needs the path to the file `aa1` under the directory `data/aa` in the scapp folder where SCAPP was installed.
> 
> Let me know if that works - if so, it should be a quick fix to SCAPP to have it use db_version 4.

sorry, it is my mistake, query is not correct

**Comment by aaa-meituo-aaa** [comment] 2020-10-08 15:05
this is the new problem, enev i changed the query
(scapp) hsv709@pallas:/mibi/Wanli/test_scapp$ tblastn -db sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb -db_gencode 11 -query /mibi/Wanli/anaconda/pkgs/scapp-0.1.3-py_1/site-packages/scapp/data/aa/aa1 -out sacpp_darwin/intermediate_files/aa1_blastdb.out -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
BLAST Database error: No alias or index file found for nucleotide database [sacpp_darwin/intermediate_files/DP-Sample031-S31-001_contigs.fastg.blastdb] in search path [/mibi/users/Wanli/test_scapp:/data/blast:]

**Comment by aaa-meituo-aaa** [comment] 2020-10-08 15:06
and this file is empty "DP-Sample031-S31-001_contigs.fastg.blastdb"

**Comment by dpellow** [comment] 2020-10-08 15:15
Oh I see - this looks like the BLAST database doesn't exist, so maybe `makeblastdb` didn't finish correctly.

Can you first try to clear out all the old files (or use a new directory), then run `makeblastdb` with your input file, desired output location and the blastdb_version 4 option. The command should look like: `makeblastdb -in <input file path> -dbtype nucl -blastdb_version 4 -out <output path>`

Then check that makeblastdb created the blast database.

Then run tblastn with this database, and the aa1 file as the query. The command should look like:  `tblastn -db <path to db (same as output path of makeblastdb)> -db_gencode 11 -query <path to scapp>/scapp/data/aa/aa1 -out <output file path> -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"

Does that work? Make sure the blast database exists first - let me know if that is a problem.
Thanks!

**Comment by aaa-meituo-aaa** [comment] 2020-10-09 09:30
> -out <output file path> -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"

hi! this is work.
![image](https://user-images.githubusercontent.com/58076352/95567110-0f4af280-0a55-11eb-9955-e5cf28ac01c1.png)

**Comment by aaa-meituo-aaa** [comment] 2020-10-09 09:30
> > -out  -num_threads 4 -outfmt "6 qseqid sseqid length pident qlen slen evalue"
> 
> hi! this is work.
> ![image](https://user-images.githubusercontent.com/58076352/95567110-0f4af280-0a55-11eb-9955-e5cf28ac01c1.png)

this is the outfile of tblastn

**Comment by dpellow** [comment] 2020-10-09 09:47
OK great thanks! I will put that change into SCAPP and submit the update to bioconda. Will let you know here once the new version is accepted into bioconda.

**Comment by aaa-meituo-aaa** [comment] 2020-10-09 10:31
> OK great thanks! I will put that change into SCAPP and submit the update to bioconda. Will let you know here once the new version is accepted into bioconda.

ok! thanks!

**Comment by dpellow** [comment] 2020-10-10 18:07
I have updated this in the code and SCAPP v0.1.4 is now on bioconda. If you re-install SCAPP from bioconda it should no longer have this problem. Please let me know if you have more problems with the new version.
I will post a summary of this thread and close it.

**Comment by dpellow** [comment] 2020-10-10 18:18
Summary of thread:
User ran into the same issue as issue #12 - tblastn seg faults on some inputs when multi-threading. This is fixed in BLAST version 2.10.1 (See NCBI release notes [here](https://www.ncbi.nlm.nih.gov/books/NBK131777/#_Blast_ReleaseNotes_BLAST_2_10_1_June_8_2_))
User had some difficulty installing BLAST 2.10.1 - I updated the Bioconda recipe, so that this version is now installed automatically.
However, new version of BLAST created a memory problem when making the BLAST database on user's system. Based on indication in makeblastdb documentation [here](https://www.ncbi.nlm.nih.gov/books/NBK279684/) I changed the implementation of makeblastdb to use database version 4. This seems to have solved the problem.

**Closed by dpellow** 2020-10-10 18:18 UTC

**Comment by aaa-meituo-aaa** [comment] 2020-10-11 13:34
> Summary of thread:
> User ran into the same issue as issue #12 - tblastn seg faults on some inputs when multi-threading. This is fixed in BLAST version 2.10.1 (See NCBI release notes [here](https://www.ncbi.nlm.nih.gov/books/NBK131777/#_Blast_ReleaseNotes_BLAST_2_10_1_June_8_2_))
> User had some difficulty installing BLAST 2.10.1 - I updated the Bioconda recipe, so that this version is now installed automatically.
> However, new version of BLAST created a memory problem when making the BLAST database on user's system. Based on indication in makeblastdb documentation [here](https://www.ncbi.nlm.nih.gov/books/NBK279684/) I changed the implementation of makeblastdb to use database version 4. This seems to have solved the problem.

thanks, it works now

**Comment by dpellow** [comment] 2020-10-11 13:53
Great! Hope you are able to use it to identify interesting plasmids. Let us know if you run into any other problems

**Comment by aaa-meituo-aaa** [comment] 2020-10-12 08:10
> Great! Hope you are able to use it to identify interesting plasmids. Let us know if you run into any other problems

(scapp-new) hsv709@pallas:/mibi/Wanli/benchmark$ scapp -g assembly-out/assembly_graph.fastg -k 99  -r1 R1.fq.gz -r2 R2.fq.gz -o scapp-out -p 20

Creating BAM file of read mappings with BWA
Traceback (most recent call last):
  File "/mibi/Wanli/anaconda/envs/scapp-new/bin/scapp", line 10, in <module>
    sys.exit(main())
  File "/mibi/Wanli/anaconda/envs/scapp-new/lib/python3.7/site-packages/scapp/scapp.py", line 234, in main
    subprocess.check_call(cmd,stderr=subprocess.STDOUT, stdout=bwa_outfile, shell=True)
  File "/mibi/Wanli/anaconda/envs/scapp-new/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bwa mem -t 20 scapp-out/intermediate_files/assembly_graph.nodes.fasta R1.fq.gz R2.fq.gz | samtools  view -buS -@ 19 - > scapp-out/intermediate_files/reads_pe.bam' returned non-zero exit status 1.

today, i run another data, but raise error again, like this.  the fastg file is output from spades, and the assembly k-mer are 21,33,55,77,99, so the k is scapp is 99.  before this, the assembler i used is megahit. so i don`t know whether this is the problem

**Comment by dpellow** [comment] 2020-10-12 08:59
I don't think the problem has to do with the assembler.
How did you install SCAPP, what version of SCAPP is it?
Can you let me know what version of BWA you have? (If you type BWA in the command line, the version will be listed at the top of the output).
What are the contents of the file `scapp-out/logs/bwa_out.log`?

**Comment by dpellow** [comment] 2020-10-12 09:25
I have moved this question about the error in the alignment step (BWA or samtools error) to issue #15. Please continue that open issue.
